### ISSUE TITLE
logging consistency in radical stack

### ISSUE THREAD

**Issue by andre-merzky** [radical-cybertools/radical.saga#631]
This is not specifically a SAGA ticket.  Point is, that we have a discontinuity in logging between RP and RS: a RP session inherits the RS session, but the RP session has a logging handle which is not passed to the  RS layer, which uses it's own logging handle.  The same holds for other layers (RA/RU, RS/RU, ...).  

This is not a critical issue, since logging is generally available - but it makes cross-layer debugging harder than it should be.

**Comment by iparask** [comment]
Yes.

**Comment by andre-merzky** [comment]
This is now implemented via consistent and universal log level (`RADICAL_LOG_LVL`) and log target (`RADICAL_LOG_TGT`) control, and will be released in v0.60.

**Comment by iparask** [comment]
So this can be closed!

**Comment by andre-merzky** [comment]
Well, yes - but usually after release :)

**Comment by andre-merzky** [comment]
Also, it is still not passing the log handles to the SAGA session :-/
