### ISSUE TITLE
checkjob vs qstat

### ISSUE THREAD

**Issue by DanilaOleynik** [radical-cybertools/radical.saga#659]
https://github.com/radical-cybertools/saga-python/blob/d0b303525b7bcfc16c235382941f217e0b22138b/src/saga/adaptors/torque/torquejob.py#L726

Hello, 

Here is my observation of usage of 'checkjob' vs 'qstat' with TORQUE/MOAB (i think will work with Maui as well). qstat works well, while job managed by resource manager, so it's ok while job queued or running, but job in final state (completed, failed etc.) are not available through resources manager after certain period of time (from time to time a short period). 
In general message like: "Unknown Job Id Error 3884934.titan-moab.ccs.ornl.gov" 
does not mean real final error, but mean usage of other tool for retrieving job related information.  Equal (or even more detailed) information is retrivable from scheduler by quering: checkjob. Information available more longer period of time (up to few days) so it works a bit better for retriving of job metrics, timing etc. 'checkjob' is defently available for 'big guys' like Titan, Blue Waters and i assume for other Cray machines. 

Cheers,
Danila

Small example: 

 `[Mon Feb 26 06:24:40 doleynik@dtn35:~ ] $ qstat 3884934
qstat: Unknown Job Id Error 3884934.titan-moab.ccs.ornl.gov
[Mon Feb 26 06:24:47 doleynik@dtn35:~ ] $ checkjob 3884934
job 3884934

AName: SAGA-Python-TORQUEJobScript.r4oKzE
State: Completed 
Completion Code: 0  Time: Sun Feb 25 22:38:47
Creds:  user:doleynik  group:doleynik  account:CSC108  class:batch  qos:smallmaxjobs
WallTime:   00:49:16 of 1:59:00
BecameEligible: Sun Feb 25 21:31:46
SubmitTime: Sun Feb 25 21:31:36
  (Time Queued  Total: 00:17:55  Eligible: 00:17:50)

Job Templates: smallmaxjobs
TemplateSets:  DEFAULT,smallmaxjobs.set
Total Requested Tasks: 800

Req[0]  TaskCount: 800  Partition: titan
GMetric[energy_used]  Current: 0.00  Min: 0.00  Max: 0.00  Avg: 0.00 Total: 0.00

Allocated Nodes:
[6806:16][6807:16][6804:16][6805:16][6730:16][6731:16]
[5556:16][5557:16][5482:16][5483:16][5480:16][5481:16]
[5558:16][5559:16][5192:16][5193:16][5270:16][5271:16]
[3944:16][3945:16][4023:16][4020:16][4021:16][5194:16]
[5195:16][5268:16][5269:16][3946:16][3947:16][3948:16]
[3949:16][4018:16][4019:16][4016:16][4017:16][3950:16]
[3951:16][5264:16][5265:16][5198:16][5199:16][5196:16]
[5197:16][5266:16][5267:16][5484:16][5485:16][5554:16]
[5555:16][5552:16]

SystemID:   titan
SystemJID:  3884934
Notification Events: JobFail

IWD:            /autofs/nccs-svm1_home1/doleynik
StartCount:     1
BypassCount:    1
Execution Partition:  titan
Flags:          BACKFILL,RESTARTABLE,FSVIOLATION
Attr:           BACKFILL,FSVIOLATION,checkpoint,smallmaxjobs.set
StartPriority:  -528322
IterationJobRank: 0
PE:             800.00

[Mon Feb 26 06:24:57 doleynik@dtn35:~ ] $ `

**Comment by andre-merzky** [comment]
See also #180

**Comment by andre-merzky** [comment]
Danila, is this still an issue which needs fixing?  Sorry for dropping the ball on this :/

**Comment by DanilaOleynik** [comment]
I had to implement a workaround on the upper level in Harvester for Titan, it works.  Will be nice to have this possibility in the framework to be able to get complete info in one place.

**Comment by andre-merzky** [comment]
Do you have a code snippet we can steal? :-D

**Comment by DanilaOleynik** [comment]
Here is some: https://github.com/PanDAWMS/panda-harvester/blob/65f7f53c77fd8f5ae7d399355eaab6f123e4802c/pandaharvester/harvestermisc/titan_utils.py#L50

**Comment by andre-merzky** [comment]
Thanks Danila!

We probably don't want to go the road of dual or mixed licensing right now (SAGA is MIT licensed), so won't copy verbatim.  But the method is easy enough to understand, and if you don't mind, we would copy the general approach to parsing the output (which we use in other adaptors in similar situations, too).  Would that be ok?

Best, Andre.

**Comment by DanilaOleynik** [comment]
Yes, sure go ahead. This method definitely not the rocket science :-) sorry for the delay, got some mess in emails
