### ISSUE TITLE
SAGA to expose environment variable about SMT setting for Summit

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.saga#707]
Just follow up ticket from an email thread with ORNL. There are no explicit env variables that expose that, we will have to look at the cpuset (at /sys/fs/cgroup/cpuset/cpuset.cpus) and parse it. Easier solution would be to have SAGA expose an env variable.

**Comment by lee212** [comment]
NAMD group needs to use SMT1 on Summit, and this ticket looks relevant to get updated. reference: https://github.com/radical-collaboration/MDFF-EnTK/issues/19
