### ISSUE TITLE
Incorrect data type reading, e.g. ssh_timeout "10.0" is string, not float in PY2

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.saga#749]
`src/radical/saga/configs/utils.json` has configuration values e.g. `ssh_timeout` with quotes that saga in python2 treats these values as a string, not numerical values. This is not an issue in python3 as `to_type` function finds correct data types according to radical-cybertools/radical.utils/pull/187.

Do we need `to_type` in py2 branch as well?

**Comment by andre-merzky** [comment]
The type conversion was introduced with the new config system which folds environment vars into config files.  That's what you see in that config file, so we do use that in Py2 indeed, and thus should indeed also backport the type conversion.

**Comment by andre-merzky** [comment]
This has been fixed by now - thanks!
