### ISSUE TITLE
Cleanup `n_nodes` for slurm_job

### ISSUE THREAD

**Issue by mtitov** [radical-cybertools/radical.saga#795]
Follow up Andre's comment at PR #794 

> 
> How about:
> 
> ```
> n_nodes = None
> if self._ppn:
>    n_nodes = ...
> 
> if total_memory:
>   assert(n_nodes)
>   mem_per_node = total_memory / n_nodes
> ```
> 
> Those calculations are, at the end, really independent from the specific target resource, and should also work for resources we don't really check in the code.

@andre-merzky agree to re-work current implementation according to your changes
and would include here discussion about `self._ppn` with different queues: I saw you've used `self.rm.queue` to set `self._ppn` ([here](https://github.com/radical-cybertools/radical.saga/blob/project/covid-19/src/radical/saga/adaptors/slurm/slurm_job.py#L405)), so `self.rm` "knows" about the queue? I thought it is only available at `_job_run` ([here](https://github.com/radical-cybertools/radical.saga/blob/project/covid-19/src/radical/saga/adaptors/slurm/slurm_job.py#L567)). I like your approach here as well

**Comment by andre-merzky** [comment]
Ouch, the `self.rm.queue` was totally wrong, thanks for catching that!  I did a merge from an old location today and apparently did not think clearly when 'fixing' this line (the resource manager URL has no `queue` element).  So you are right, we will have to delay those decisions until `_job_run`.
