### ISSUE TITLE
working_directory in slurm

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.saga#830]
The slurm adaptor currently has some hardcoded exceptions for switching between the 4 years old old behavior of `--workdir` and `--chdir`. Its probably time to change the default. What is probably an even better solution is to use the shorthand `-D` as that works for both versions.

**Comment by andre-merzky** [comment]
Thanks Mark - this should be addressed in #831

**Comment by marksantcroos** [comment]
Thanks!
