### ISSUE TITLE
additional slurm state: OUT_OF_MEMORY

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.saga#832]
Can you add the `OUT_OF_MEMORY` state mapping to `FAILED`? (per https://slurm.schedmd.com/squeue.html)

```elif slurmjs in ['OOM', "OUT_OF_MEMORY"  ]: return c.FAILED```

**Comment by marksantcroos** [comment]
Thanks @andre-merzky

**Comment by andre-merzky** [comment]
np - glad you are still using this stuff.... :-)  Let us know if you need anything else!
